pfinyg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tasks/", include("tasks.urls"))
]

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name = "index"),
    ]

tasks/models.py
from django.contrib.auth.models import User
from django.core import validators
from django.db import models

# Create your models here.
class Task(models.Model):
    taskName = models.CharField(max_length = 150, blank = False)
    taskImportance = models.IntegerField(default = 3,
                                         blank = False,
                                         validators = [
                                            validators.MinValueValidator(1),
                                            validators.MaxValueValidator(5)
                                            ])
    dueDate = models.DateField(blank = True, null = True)
    doneDate = models.DateField(blank = True, null = True)
    comment = models.CharField(max_length = 1024, blank = True, null = True)
    createDatetime = models.DateTimeField(auto_now_add=True)
    updateDatetime = models.DateTimeField(auto_now = True)
    completedDatetime = models.DateTimeField(blank = True, null = True)
    taskOwnerId = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "tasks")

    def __str__(self):
        return self.taskName

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields =("taskName", "taskImportance", "dueDate", "comment")

tasks/views.py
from django.shortcuts import render
from django.http import HttpResponse



# Create your views here.
def index(request, opt = None):
    return HttpResponse("hello world")

tasks/templates/tasks/index.html
{% extends "base.html" %}
{% block content %}
<h2>タスク一覧</h2>

<form action={% url "tasks:new" %} method="POST">
  {% csrf_token %}
  {{ newForm.as_p }}
  <button type="submit">登録</button>
</form>

{% for f in forms %}
<form action={% url "tasks:new" %} method="POST">
  {% csrf_token %}
  {{ f.form.taskName }}
  {{ f.form.dueDate }}
  <button type="submit">編集</button>
</form>
{% endfor %}


<br>
debug<br><br>

{% for task in tasks %}
  {{ task.taskName }}
  {{ task.dueDate }}
  {{ task.id }}
  <br>
{% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Plant Flowers in Your Garden</title>
</head>
<body>
<div class="container">
    <header>
      <p class="site-name"><a href="{% url 'tasks:index' %}">Plant Flowers in Your Garden</a></p>
      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" class="logout">Logout</a>
      {% else %}
        <a href="{% url 'login' %}" class="login">Login</a>
        <a href="{% url 'accounts:signup' %}" class="signup">Sign Up</a>
      {% endif %}
    </header>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</div>
</body>
</html>